{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4eae7422-3327-4179-a2ad-a5fd38d40339",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting inference-gpu\n",
      "  Using cached inference_gpu-0.54.1-py3-none-any.whl.metadata (24 kB)\n",
      "Collecting aiortc~=1.9.0 (from inference-gpu)\n",
      "  Using cached aiortc-1.9.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)\n",
      "Collecting APScheduler<4.0.0,>=3.10.1 (from inference-gpu)\n",
      "  Using cached APScheduler-3.11.0-py3-none-any.whl.metadata (6.4 kB)\n",
      "Collecting asyncua~=1.1.5 (from inference-gpu)\n",
      "  Using cached asyncua-1.1.6-py3-none-any.whl.metadata (9.6 kB)\n",
      "Requirement already satisfied: cachetools<6.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (5.3.0)\n",
      "Collecting cython~=3.0.0 (from inference-gpu)\n",
      "  Using cached Cython-3.0.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.3 kB)\n",
      "Requirement already satisfied: python-dotenv~=1.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (1.0.1)\n",
      "Requirement already satisfied: fastapi<0.116,>=0.100 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.115.6)\n",
      "Collecting numpy<2.3.0,>=2.0.0 (from inference-gpu)\n",
      "  Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)\n",
      "Collecting opencv-python<=4.10.0.84,>=4.8.1.78 (from inference-gpu)\n",
      "  Using cached opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
      "Collecting opencv-contrib-python<=4.10.0.84,>=4.8.1.78 (from inference-gpu)\n",
      "  Using cached opencv_contrib_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
      "Collecting pillow<12.0,>=11.0 (from inference-gpu)\n",
      "  Using cached pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)\n",
      "Collecting prometheus-fastapi-instrumentator<=6.0.0 (from inference-gpu)\n",
      "  Using cached prometheus_fastapi_instrumentator-6.0.0-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting redis~=5.0.0 (from inference-gpu)\n",
      "  Using cached redis-5.0.8-py3-none-any.whl.metadata (9.2 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (2.32.5)\n",
      "Requirement already satisfied: rich<13.10.0,>=13.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (13.9.4)\n",
      "Collecting supervision<0.26.0,>=0.25.1 (from inference-gpu)\n",
      "  Using cached supervision-0.25.1-py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: pybase64~=1.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (1.0.2)\n",
      "Requirement already satisfied: scikit-image<=0.25.2,>=0.19.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.20.0)\n",
      "Collecting requests-toolbelt~=1.0.0 (from inference-gpu)\n",
      "  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: wheel<=0.45.1,>=0.38.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.40.0)\n",
      "Requirement already satisfied: setuptools>=70.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (80.9.0)\n",
      "Requirement already satisfied: networkx<4.0.0,>=3.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (3.1)\n",
      "Requirement already satisfied: pydantic<2.12.0,>=2.8.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (2.10.4)\n",
      "Collecting pydantic-settings<2.8 (from inference-gpu)\n",
      "  Using cached pydantic_settings-2.7.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "Requirement already satisfied: openai<2.0.0,>=1.12.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (1.58.1)\n",
      "Requirement already satisfied: structlog<25.0.0,>=24.1.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (24.4.0)\n",
      "Requirement already satisfied: zxing-cpp~=2.2.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (2.2.0)\n",
      "Collecting boto3<=1.35.60 (from inference-gpu)\n",
      "  Using cached boto3-1.35.60-py3-none-any.whl.metadata (6.7 kB)\n",
      "Requirement already satisfied: typing_extensions<=4.12.2,>=4.8.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (4.12.2)\n",
      "Requirement already satisfied: pydot~=2.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (2.0.0)\n",
      "Collecting shapely<2.1.0,>=2.0.4 (from inference-gpu)\n",
      "  Using cached shapely-2.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)\n",
      "Collecting tldextract~=5.1.2 (from inference-gpu)\n",
      "  Using cached tldextract-5.1.3-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting packaging~=24.0 (from inference-gpu)\n",
      "  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)\n",
      "Collecting anthropic~=0.49.0 (from inference-gpu)\n",
      "  Using cached anthropic-0.49.0-py3-none-any.whl.metadata (24 kB)\n",
      "Collecting pandas<3.0.0,>=2.2.3 (from inference-gpu)\n",
      "  Using cached pandas-2.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)\n",
      "Requirement already satisfied: paho-mqtt~=1.6.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (1.6.1)\n",
      "Collecting pytest<9.0.0,>=8.0.0 (from inference-gpu)\n",
      "  Using cached pytest-8.4.1-py3-none-any.whl.metadata (7.7 kB)\n",
      "Requirement already satisfied: tokenizers<0.22.0,>=0.19.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.21.1)\n",
      "Requirement already satisfied: slack-sdk~=3.33.4 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (3.33.5)\n",
      "Collecting twilio~=9.3.7 (from inference-gpu)\n",
      "  Using cached twilio-9.3.8-py2.py3-none-any.whl.metadata (12 kB)\n",
      "Requirement already satisfied: httpx~=0.28.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.28.1)\n",
      "Requirement already satisfied: pylogix==1.0.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (1.0.5)\n",
      "Requirement already satisfied: pymodbus<=3.8.3,>=3.6.9 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (3.8.3)\n",
      "Collecting backoff~=2.2.0 (from inference-gpu)\n",
      "  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: filelock<=3.17.0,>=3.12.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (3.16.1)\n",
      "Collecting onvif-zeep-async==2.0.0 (from inference-gpu)\n",
      "  Using cached onvif_zeep_async-2.0.0-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: simple-pid~=2.0.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (2.0.1)\n",
      "Requirement already satisfied: qrcode~=8.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (8.0)\n",
      "Collecting onnxruntime-gpu<1.22.0,>=1.15.1 (from inference-gpu)\n",
      "  Using cached onnxruntime_gpu-1.21.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)\n",
      "Collecting docker<8.0.0,>=7.0.0 (from inference-gpu)\n",
      "  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "Requirement already satisfied: click<8.2.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (8.1.8)\n",
      "Requirement already satisfied: typer<=0.16.0,>=0.9.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (0.15.4)\n",
      "Requirement already satisfied: PyYAML~=6.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (6.0)\n",
      "Requirement already satisfied: tqdm<5.0.0,>=4.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (4.65.0)\n",
      "Requirement already satisfied: nvidia-ml-py<13.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (12.560.30)\n",
      "Requirement already satisfied: py-cpuinfo~=9.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-gpu) (9.0.0)\n",
      "Collecting aiohttp<=3.10.11,>=3.9.0 (from inference-gpu)\n",
      "  Using cached aiohttp-3.10.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)\n",
      "Collecting dataclasses-json~=0.6.0 (from inference-gpu)\n",
      "  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)\n",
      "Collecting zeep<5.0.0,>=4.2.1 (from zeep[async]<5.0.0,>=4.2.1->onvif-zeep-async==2.0.0->inference-gpu)\n",
      "  Using cached zeep-4.3.1-py3-none-any.whl.metadata (4.3 kB)\n",
      "Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<=3.10.11,>=3.9.0->inference-gpu)\n",
      "  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-gpu) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-gpu) (22.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-gpu) (1.3.3)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-gpu) (6.0.4)\n",
      "Collecting yarl<2.0,>=1.12.0 (from aiohttp<=3.10.11,>=3.9.0->inference-gpu)\n",
      "  Using cached yarl-1.20.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (73 kB)\n",
      "Requirement already satisfied: async-timeout<6.0,>=4.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-gpu) (4.0.2)\n",
      "Collecting aioice<1.0.0,>=0.9.0 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached aioice-0.10.1-py3-none-any.whl.metadata (4.1 kB)\n",
      "Collecting av<13.0.0,>=9.0.0 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached av-12.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: cffi>=1.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiortc~=1.9.0->inference-gpu) (1.15.1)\n",
      "Collecting cryptography>=42.0.0 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached cryptography-45.0.7-cp37-abi3-manylinux_2_34_x86_64.whl.metadata (5.7 kB)\n",
      "Collecting google-crc32c>=1.1 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached google_crc32c-1.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)\n",
      "Requirement already satisfied: pyee>=9.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiortc~=1.9.0->inference-gpu) (13.0.0)\n",
      "Collecting pylibsrtp>=0.10.0 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached pylibsrtp-0.12.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)\n",
      "Collecting pyopenssl>=24.0.0 (from aiortc~=1.9.0->inference-gpu)\n",
      "  Using cached pyopenssl-25.1.0-py3-none-any.whl.metadata (17 kB)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from anthropic~=0.49.0->inference-gpu) (4.9.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from anthropic~=0.49.0->inference-gpu) (1.9.0)\n",
      "Requirement already satisfied: jiter<1,>=0.4.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from anthropic~=0.49.0->inference-gpu) (0.8.2)\n",
      "Requirement already satisfied: sniffio in /opt/conda/envs/rapids/lib/python3.10/site-packages (from anthropic~=0.49.0->inference-gpu) (1.3.0)\n",
      "Requirement already satisfied: tzlocal>=3.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from APScheduler<4.0.0,>=3.10.1->inference-gpu) (5.3.1)\n",
      "Requirement already satisfied: aiofiles in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (22.1.0)\n",
      "Requirement already satisfied: aiosqlite in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (0.18.0)\n",
      "Requirement already satisfied: python-dateutil in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (2.8.2)\n",
      "Requirement already satisfied: pytz in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (2023.3)\n",
      "Requirement already satisfied: sortedcontainers in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (2.4.0)\n",
      "Requirement already satisfied: wait-for2==0.3.2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from asyncua~=1.1.5->inference-gpu) (0.3.2)\n",
      "Collecting botocore<1.36.0,>=1.35.60 (from boto3<=1.35.60->inference-gpu)\n",
      "  Using cached botocore-1.35.99-py3-none-any.whl.metadata (5.7 kB)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from boto3<=1.35.60->inference-gpu) (1.0.1)\n",
      "Collecting s3transfer<0.11.0,>=0.10.0 (from boto3<=1.35.60->inference-gpu)\n",
      "  Using cached s3transfer-0.10.4-py3-none-any.whl.metadata (1.7 kB)\n",
      "Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json~=0.6.0->inference-gpu)\n",
      "  Using cached marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)\n",
      "Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json~=0.6.0->inference-gpu)\n",
      "  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)\n",
      "Requirement already satisfied: urllib3>=1.26.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from docker<8.0.0,>=7.0.0->inference-gpu) (1.26.15)\n",
      "Requirement already satisfied: starlette<0.42.0,>=0.40.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from fastapi<0.116,>=0.100->inference-gpu) (0.41.3)\n",
      "Requirement already satisfied: certifi in /opt/conda/envs/rapids/lib/python3.10/site-packages (from httpx~=0.28.1->inference-gpu) (2022.12.7)\n",
      "Requirement already satisfied: httpcore==1.* in /opt/conda/envs/rapids/lib/python3.10/site-packages (from httpx~=0.28.1->inference-gpu) (1.0.5)\n",
      "Requirement already satisfied: idna in /opt/conda/envs/rapids/lib/python3.10/site-packages (from httpx~=0.28.1->inference-gpu) (3.4)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from httpcore==1.*->httpx~=0.28.1->inference-gpu) (0.14.0)\n",
      "Requirement already satisfied: coloredlogs in /opt/conda/envs/rapids/lib/python3.10/site-packages (from onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (15.0.1)\n",
      "Requirement already satisfied: flatbuffers in /opt/conda/envs/rapids/lib/python3.10/site-packages (from onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (23.5.26)\n",
      "Requirement already satisfied: protobuf in /opt/conda/envs/rapids/lib/python3.10/site-packages (from onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (4.25.6)\n",
      "Requirement already satisfied: sympy in /opt/conda/envs/rapids/lib/python3.10/site-packages (from onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (1.13.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pandas<3.0.0,>=2.2.3->inference-gpu) (2025.2)\n",
      "Requirement already satisfied: prometheus-client<1.0.0,>=0.8.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from prometheus-fastapi-instrumentator<=6.0.0->inference-gpu) (0.21.1)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pydantic<2.12.0,>=2.8.0->inference-gpu) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.27.2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pydantic<2.12.0,>=2.8.0->inference-gpu) (2.27.2)\n",
      "Requirement already satisfied: pyparsing>=3 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pydot~=2.0.0->inference-gpu) (3.0.9)\n",
      "Requirement already satisfied: exceptiongroup>=1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pytest<9.0.0,>=8.0.0->inference-gpu) (1.1.1)\n",
      "Requirement already satisfied: iniconfig>=1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pytest<9.0.0,>=8.0.0->inference-gpu) (2.0.0)\n",
      "Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pytest<9.0.0,>=8.0.0->inference-gpu) (1.6.0)\n",
      "Requirement already satisfied: pygments>=2.7.2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pytest<9.0.0,>=8.0.0->inference-gpu) (2.15.0)\n",
      "Requirement already satisfied: tomli>=1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from pytest<9.0.0,>=8.0.0->inference-gpu) (2.0.1)\n",
      "Collecting async-timeout<6.0,>=4.0 (from aiohttp<=3.10.11,>=3.9.0->inference-gpu)\n",
      "  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from requests<3.0.0,>=2.32.0->inference-gpu) (2.1.1)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from rich<13.10.0,>=13.0.0->inference-gpu) (3.0.0)\n",
      "Requirement already satisfied: scipy>=1.8 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from scikit-image<=0.25.2,>=0.19.0->inference-gpu) (1.10.1)\n",
      "Requirement already satisfied: imageio>=2.4.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from scikit-image<=0.25.2,>=0.19.0->inference-gpu) (2.27.0)\n",
      "Requirement already satisfied: tifffile>=2019.7.26 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from scikit-image<=0.25.2,>=0.19.0->inference-gpu) (2023.4.12)\n",
      "Requirement already satisfied: PyWavelets>=1.1.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from scikit-image<=0.25.2,>=0.19.0->inference-gpu) (1.4.1)\n",
      "Requirement already satisfied: lazy_loader>=0.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from scikit-image<=0.25.2,>=0.19.0->inference-gpu) (0.2)\n",
      "Requirement already satisfied: contourpy>=1.0.7 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-gpu) (1.0.7)\n",
      "Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-gpu) (0.7.1)\n",
      "Requirement already satisfied: matplotlib>=3.6.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-gpu) (3.7.1)\n",
      "Collecting requests-file>=1.4 (from tldextract~=5.1.2->inference-gpu)\n",
      "  Using cached requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from tokenizers<0.22.0,>=0.19.0->inference-gpu) (0.31.2)\n",
      "Requirement already satisfied: PyJWT<3.0.0,>=2.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from twilio~=9.3.7->inference-gpu) (2.10.1)\n",
      "Collecting aiohttp-retry==2.8.3 (from twilio~=9.3.7->inference-gpu)\n",
      "  Using cached aiohttp_retry-2.8.3-py3-none-any.whl.metadata (8.9 kB)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from typer<=0.16.0,>=0.9.0->inference-gpu) (1.5.4)\n",
      "Requirement already satisfied: dnspython>=2.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aioice<1.0.0,>=0.9.0->aiortc~=1.9.0->inference-gpu) (2.7.0)\n",
      "Requirement already satisfied: ifaddr>=0.2.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aioice<1.0.0,>=0.9.0->aiortc~=1.9.0->inference-gpu) (0.2.0)\n",
      "Requirement already satisfied: pycparser in /opt/conda/envs/rapids/lib/python3.10/site-packages (from cffi>=1.0.0->aiortc~=1.9.0->inference-gpu) (2.21)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers<0.22.0,>=0.19.0->inference-gpu) (2023.6.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<13.10.0,>=13.0.0->inference-gpu) (0.1.2)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-gpu) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-gpu) (4.39.3)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-gpu) (1.4.4)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from python-dateutil->asyncua~=1.1.5->inference-gpu) (1.16.0)\n",
      "INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting scipy>=1.8 (from scikit-image<=0.25.2,>=0.19.0->inference-gpu)\n",
      "  Using cached scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)\n",
      "Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json~=0.6.0->inference-gpu)\n",
      "  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: propcache>=0.2.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp<=3.10.11,>=3.9.0->inference-gpu) (0.3.2)\n",
      "Collecting isodate>=0.5.4 (from zeep<5.0.0,>=4.2.1->zeep[async]<5.0.0,>=4.2.1->onvif-zeep-async==2.0.0->inference-gpu)\n",
      "  Using cached isodate-0.7.2-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting lxml>=4.6.0 (from zeep<5.0.0,>=4.2.1->zeep[async]<5.0.0,>=4.2.1->onvif-zeep-async==2.0.0->inference-gpu)\n",
      "  Using cached lxml-6.0.1-cp310-cp310-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)\n",
      "Requirement already satisfied: platformdirs>=1.4.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from zeep<5.0.0,>=4.2.1->zeep[async]<5.0.0,>=4.2.1->onvif-zeep-async==2.0.0->inference-gpu) (4.3.6)\n",
      "Requirement already satisfied: humanfriendly>=9.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from coloredlogs->onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (10.0)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from sympy->onnxruntime-gpu<1.22.0,>=1.15.1->inference-gpu) (1.3.0)\n",
      "Using cached inference_gpu-0.54.1-py3-none-any.whl (2.5 MB)\n",
      "Using cached onvif_zeep_async-2.0.0-py2.py3-none-any.whl (190 kB)\n",
      "Using cached aiohttp-3.10.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)\n",
      "Using cached aiortc-1.9.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)\n",
      "Using cached anthropic-0.49.0-py3-none-any.whl (243 kB)\n",
      "Using cached APScheduler-3.11.0-py3-none-any.whl (64 kB)\n",
      "Using cached asyncua-1.1.6-py3-none-any.whl (1.1 MB)\n",
      "Using cached backoff-2.2.1-py3-none-any.whl (15 kB)\n",
      "Using cached boto3-1.35.60-py3-none-any.whl (139 kB)\n",
      "Using cached Cython-3.0.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)\n",
      "Using cached dataclasses_json-0.6.7-py3-none-any.whl (28 kB)\n",
      "Using cached docker-7.1.0-py3-none-any.whl (147 kB)\n",
      "Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)\n",
      "Using cached onnxruntime_gpu-1.21.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (280.8 MB)\n",
      "Using cached opencv_contrib_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68.7 MB)\n",
      "Using cached opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)\n",
      "Using cached packaging-24.2-py3-none-any.whl (65 kB)\n",
      "Using cached pandas-2.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)\n",
      "Using cached pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)\n",
      "Using cached prometheus_fastapi_instrumentator-6.0.0-py3-none-any.whl (18 kB)\n",
      "Using cached pydantic_settings-2.7.1-py3-none-any.whl (29 kB)\n",
      "Using cached pytest-8.4.1-py3-none-any.whl (365 kB)\n",
      "Using cached redis-5.0.8-py3-none-any.whl (255 kB)\n",
      "Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)\n",
      "Using cached shapely-2.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)\n",
      "Using cached supervision-0.25.1-py3-none-any.whl (181 kB)\n",
      "Using cached tldextract-5.1.3-py3-none-any.whl (104 kB)\n",
      "Using cached twilio-9.3.8-py2.py3-none-any.whl (1.8 MB)\n",
      "Using cached aiohttp_retry-2.8.3-py3-none-any.whl (9.8 kB)\n",
      "Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)\n",
      "Using cached aioice-0.10.1-py3-none-any.whl (24 kB)\n",
      "Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)\n",
      "Using cached av-12.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.5 MB)\n",
      "Using cached botocore-1.35.99-py3-none-any.whl (13.3 MB)\n",
      "Using cached cryptography-45.0.7-cp37-abi3-manylinux_2_34_x86_64.whl (4.4 MB)\n",
      "Using cached google_crc32c-1.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38 kB)\n",
      "Using cached marshmallow-3.26.1-py3-none-any.whl (50 kB)\n",
      "Using cached pylibsrtp-0.12.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)\n",
      "Using cached pyopenssl-25.1.0-py3-none-any.whl (56 kB)\n",
      "Using cached requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)\n",
      "Using cached s3transfer-0.10.4-py3-none-any.whl (83 kB)\n",
      "Using cached scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)\n",
      "Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)\n",
      "Using cached yarl-1.20.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (326 kB)\n",
      "Using cached zeep-4.3.1-py3-none-any.whl (101 kB)\n",
      "Using cached isodate-0.7.2-py3-none-any.whl (22 kB)\n",
      "Using cached lxml-6.0.1-cp310-cp310-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.3 MB)\n",
      "Using cached mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)\n",
      "Installing collected packages: yarl, pillow, packaging, numpy, mypy-extensions, lxml, isodate, google-crc32c, cython, backoff, av, async-timeout, APScheduler, aioice, aiohappyeyeballs, typing-inspect, shapely, scipy, requests-toolbelt, requests-file, redis, pytest, pylibsrtp, pandas, opencv-python, opencv-contrib-python, onnxruntime-gpu, marshmallow, docker, cryptography, botocore, aiohttp, zeep, tldextract, s3transfer, pyopenssl, pydantic-settings, dataclasses-json, anthropic, aiohttp-retry, twilio, supervision, prometheus-fastapi-instrumentator, boto3, asyncua, aiortc, onvif-zeep-async, inference-gpu\n",
      "\u001b[33m  WARNING: The scripts f2py and numpy-config are installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The scripts cygdb, cython and cythonize are installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The script pyav is installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The scripts py.test and pytest are installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The script onnxruntime_test is installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The script tldextract is installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The scripts uabrowse, uacall, uaclient, uadiscover, uageneratestructs, uahistoryread, uals, uaread, uaserver, uasubscribe and uawrite are installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The script onvif-cli is installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33m  WARNING: The script inference is installed in '/home/runai-home/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "cudf 23.4.0 requires cupy-cuda11x<12.0.0a0,>=9.5.0, which is not installed.\n",
      "cugraph 23.4.0 requires cupy-cuda11x<12.0.0a0,>=9.5.0, which is not installed.\n",
      "cuml 23.4.0 requires cupy-cuda11x<12.0.0a0,>=9.5.0, which is not installed.\n",
      "dask-cudf 23.4.0 requires cupy-cuda11x<12.0.0a0,>=9.5.0, which is not installed.\n",
      "aiobotocore 2.5.0 requires botocore<1.29.77,>=1.29.76, but you have botocore 1.35.99 which is incompatible.\n",
      "cudf 23.4.0 requires numba<0.57,>=0.56.4, but you have numba 0.61.2 which is incompatible.\n",
      "cudf 23.4.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.3.2 which is incompatible.\n",
      "cudf 23.4.0 requires protobuf<4.22,>=4.21.6, but you have protobuf 4.25.6 which is incompatible.\n",
      "cupy 11.6.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.6 which is incompatible.\n",
      "dask-cuda 23.4.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.3.2 which is incompatible.\n",
      "dask-cudf 23.4.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.3.2 which is incompatible.\n",
      "lda 2.0.0 requires numpy<2.0,>=1.13.0, but you have numpy 2.2.6 which is incompatible.\n",
      "s3fs 2023.4.0 requires fsspec==2023.4.0, but you have fsspec 2023.6.0 which is incompatible.\n",
      "segmentation-models-pytorch 0.3.3 requires timm==0.9.2, but you have timm 1.0.19 which is incompatible.\n",
      "spacy 3.7.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.15.4 which is incompatible.\n",
      "vllm 0.8.5.post1 requires prometheus-fastapi-instrumentator>=7.0.0, but you have prometheus-fastapi-instrumentator 6.0.0 which is incompatible.\n",
      "weasel 0.3.4 requires typer<0.10.0,>=0.3.0, but you have typer 0.15.4 which is incompatible.\n",
      "xarray 2023.3.0 requires pandas<2,>=1.4, but you have pandas 2.3.2 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed APScheduler-3.11.0 aiohappyeyeballs-2.6.1 aiohttp-3.10.11 aiohttp-retry-2.8.3 aioice-0.10.1 aiortc-1.9.0 anthropic-0.49.0 async-timeout-5.0.1 asyncua-1.1.6 av-12.3.0 backoff-2.2.1 boto3-1.35.60 botocore-1.35.99 cryptography-45.0.7 cython-3.0.12 dataclasses-json-0.6.7 docker-7.1.0 google-crc32c-1.7.1 inference-gpu-0.54.1 isodate-0.7.2 lxml-6.0.1 marshmallow-3.26.1 mypy-extensions-1.1.0 numpy-2.2.6 onnxruntime-gpu-1.21.1 onvif-zeep-async-2.0.0 opencv-contrib-python-4.10.0.84 opencv-python-4.10.0.84 packaging-24.2 pandas-2.3.2 pillow-11.3.0 prometheus-fastapi-instrumentator-6.0.0 pydantic-settings-2.7.1 pylibsrtp-0.12.0 pyopenssl-25.1.0 pytest-8.4.1 redis-5.0.8 requests-file-2.1.0 requests-toolbelt-1.0.0 s3transfer-0.10.4 scipy-1.15.3 shapely-2.0.7 supervision-0.25.1 tldextract-5.1.3 twilio-9.3.8 typing-inspect-0.9.0 yarl-1.20.1 zeep-4.3.1\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install --user inference-gpu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "592b7154-2887-4b63-bd4d-bdd826f3b2f1",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_352752/3118862054.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# import a utility function for loading Roboflow models\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mget_model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# define the image url to use for inference\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mimage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"https://media.roboflow.com/inference/people-walking.jpg\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/envs/rapids/lib/python3.10/importlib/_bootstrap.py\u001b[0m in \u001b[0;36m_handle_fromlist\u001b[0;34m(module, fromlist, import_, recursive)\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/__init__.py\u001b[0m in \u001b[0;36m__getattr__\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m     30\u001b[0m     \u001b[0;34m\"\"\"Implement lazy loading for module attributes.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     31\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0m_LAZY_ATTRIBUTES\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 32\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0m_LAZY_ATTRIBUTES\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     33\u001b[0m     \u001b[0;32mraise\u001b[0m \u001b[0mAttributeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"module 'inference' has no attribute '{name}'\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     34\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/__init__.py\u001b[0m in \u001b[0;36m<lambda>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     12\u001b[0m         \u001b[0;34m\"inference.core.interfaces.stream.inference_pipeline\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"InferencePipeline\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m     ),\n\u001b[0;32m---> 14\u001b[0;31m     \u001b[0;34m\"get_model\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;32mlambda\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0m_import_from\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"inference.models.utils\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"get_model\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     15\u001b[0m     \"get_roboflow_model\": lambda: _import_from(\n\u001b[1;32m     16\u001b[0m         \u001b[0;34m\"inference.models.utils\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"get_roboflow_model\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/__init__.py\u001b[0m in \u001b[0;36m_import_from\u001b[0;34m(module_path, attribute_name)\u001b[0m\n\u001b[1;32m     23\u001b[0m     \u001b[0;32mimport\u001b[0m \u001b[0mimportlib\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 25\u001b[0;31m     \u001b[0mmodule\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mimportlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mimport_module\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     26\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mattribute_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/envs/rapids/lib/python3.10/importlib/__init__.py\u001b[0m in \u001b[0;36mimport_module\u001b[0;34m(name, package)\u001b[0m\n\u001b[1;32m    124\u001b[0m                 \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    125\u001b[0m             \u001b[0mlevel\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 126\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0m_bootstrap\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gcd_import\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlevel\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpackage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlevel\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    127\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    128\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/models/utils.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     29\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mregistries\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mroboflow\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mget_model_type\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwarnings\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mModelDependencyMissing\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 31\u001b[0;31m from inference.models import (\n\u001b[0m\u001b[1;32m     32\u001b[0m     \u001b[0mYOLACT\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     33\u001b[0m     \u001b[0mResNetClassification\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/envs/rapids/lib/python3.10/importlib/_bootstrap.py\u001b[0m in \u001b[0;36m_handle_fromlist\u001b[0;34m(module, fromlist, import_, recursive)\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/models/__init__.py\u001b[0m in \u001b[0;36m__getattr__\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m     99\u001b[0m     \u001b[0;34m\"\"\"Implement lazy loading for model classes.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    100\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0m__all__\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 101\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mget_model_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    102\u001b[0m     \u001b[0;32mraise\u001b[0m \u001b[0mAttributeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"module 'inference.models' has no attribute '{name}'\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    103\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/models/__init__.py\u001b[0m in \u001b[0;36mget_model_class\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m     90\u001b[0m     \u001b[0;32melif\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mSTANDARD_MODELS\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     91\u001b[0m         \u001b[0mmodule_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSTANDARD_MODELS\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 92\u001b[0;31m         \u001b[0mmodule\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mimportlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mimport_module\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     93\u001b[0m         \u001b[0m_MODEL_REGISTRY\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     94\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/envs/rapids/lib/python3.10/importlib/__init__.py\u001b[0m in \u001b[0;36mimport_module\u001b[0;34m(name, package)\u001b[0m\n\u001b[1;32m    124\u001b[0m                 \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    125\u001b[0m             \u001b[0mlevel\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 126\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0m_bootstrap\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gcd_import\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlevel\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpackage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlevel\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    127\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    128\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/models/yolact/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodels\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0myolact\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0myolact_instance_segmentation\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mYOLACT\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/models/yolact/yolact_instance_segmentation.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     14\u001b[0m     \u001b[0mInstanceSegmentationPrediction\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m )\n\u001b[0;32m---> 16\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodels\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mroboflow\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mOnnxRoboflowInferenceModel\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     17\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodels\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtypes\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPreprocessReturnMetadata\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnms\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mw_np_non_max_suppression\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/core/models/roboflow.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     75\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mimage_utils\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mload_image\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     76\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0monnx\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mget_onnxruntime_execution_providers\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 77\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpreprocess\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mletterbox_image\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprepare\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     78\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mroboflow\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mget_model_id_chunks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     79\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0minference\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvisualisation\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdraw_detection_predictions\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.10/site-packages/inference/core/utils/preprocess.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mskimage\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexposure\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mrescale_intensity\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m from inference.core.env import (\n",
      "\u001b[0;32m/opt/conda/envs/rapids/lib/python3.10/site-packages/skimage/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    120\u001b[0m \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    121\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 122\u001b[0;31m         \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0m_shared\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mgeometry\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    123\u001b[0m         \u001b[0;32mdel\u001b[0m \u001b[0mgeometry\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    124\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mImportError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32mgeometry.pyx\u001b[0m in \u001b[0;36minit skimage._shared.geometry\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject"
     ]
    }
   ],
   "source": [
    "# import a utility function for loading Roboflow models\n",
    "from inference import get_model\n",
    "\n",
    "# define the image url to use for inference\n",
    "image = \"https://media.roboflow.com/inference/people-walking.jpg\"\n",
    "\n",
    "# load a pre-trained yolov8n model\n",
    "model = get_model(model_id=\"yolov8n-640\")\n",
    "\n",
    "# run inference on our chosen image, image can be a url, a numpy array, a PIL image, etc.\n",
    "results = model.infer(image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b9040ad8-34b8-406b-9174-041683fcd186",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ad7cc7ad-79c0-48db-a89d-c1d21cfc0d5c",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting inference-sdk\n",
      "  Downloading inference_sdk-0.54.1-py3-none-any.whl.metadata (20 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-sdk) (2.32.5)\n",
      "Requirement already satisfied: dataclasses-json~=0.6.0 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (0.6.7)\n",
      "Requirement already satisfied: opencv-python<=4.10.0.84,>=4.8.1.78 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (4.10.0.84)\n",
      "Requirement already satisfied: pillow<12.0,>=11.0 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (11.3.0)\n",
      "Requirement already satisfied: supervision<0.26.0,>=0.25.1 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (0.25.1)\n",
      "Requirement already satisfied: numpy<2.3.0,>=2.0.0 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (2.2.6)\n",
      "Requirement already satisfied: aiohttp<=3.10.11,>=3.9.0 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (3.10.11)\n",
      "Requirement already satisfied: backoff~=2.2.0 in /home/runai-home/.local/lib/python3.10/site-packages (from inference-sdk) (2.2.1)\n",
      "Requirement already satisfied: py-cpuinfo~=9.0.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from inference-sdk) (9.0.0)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/runai-home/.local/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (22.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (1.3.3)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/runai-home/.local/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (1.20.1)\n",
      "Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/runai-home/.local/lib/python3.10/site-packages (from aiohttp<=3.10.11,>=3.9.0->inference-sdk) (5.0.1)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/runai-home/.local/lib/python3.10/site-packages (from dataclasses-json~=0.6.0->inference-sdk) (3.26.1)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/runai-home/.local/lib/python3.10/site-packages (from dataclasses-json~=0.6.0->inference-sdk) (0.9.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from requests<3.0.0,>=2.32.0->inference-sdk) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from requests<3.0.0,>=2.32.0->inference-sdk) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from requests<3.0.0,>=2.32.0->inference-sdk) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from requests<3.0.0,>=2.32.0->inference-sdk) (2022.12.7)\n",
      "Requirement already satisfied: contourpy>=1.0.7 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (1.0.7)\n",
      "Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (0.7.1)\n",
      "Requirement already satisfied: matplotlib>=3.6.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (3.7.1)\n",
      "Requirement already satisfied: pyyaml>=5.3 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (6.0)\n",
      "Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /home/runai-home/.local/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (1.15.3)\n",
      "Requirement already satisfied: tqdm>=4.62.3 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from supervision<0.26.0,>=0.25.1->inference-sdk) (4.65.0)\n",
      "Requirement already satisfied: packaging>=17.0 in /home/runai-home/.local/lib/python3.10/site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json~=0.6.0->inference-sdk) (24.2)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (4.39.3)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (1.4.4)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (3.0.9)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (2.8.2)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/runai-home/.local/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json~=0.6.0->inference-sdk) (1.1.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json~=0.6.0->inference-sdk) (4.12.2)\n",
      "Requirement already satisfied: propcache>=0.2.1 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp<=3.10.11,>=3.9.0->inference-sdk) (0.3.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/envs/rapids/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.6.0->supervision<0.26.0,>=0.25.1->inference-sdk) (1.16.0)\n",
      "Downloading inference_sdk-0.54.1-py3-none-any.whl (43 kB)\n",
      "Installing collected packages: inference-sdk\n",
      "Successfully installed inference-sdk-0.54.1\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install inference-sdk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d7cf813-1f39-415c-8d6d-a97b796acc26",
   "metadata": {},
   "outputs": [],
   "source": [
    "from inference_sdk import InferenceHTTPClient\n",
    "\n",
    "CLIENT = InferenceHTTPClient(\n",
    "    api_url=\"https://serverless.roboflow.com\",\n",
    "    api_key=\"mfy73hKOamQcPK93XyE7\"\n",
    ")\n",
    "\n",
    "result = CLIENT.infer(, model_id=\"laparoscopic-cholecystectomy/4\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
